import os
import asyncio
from datetime import date as date_type

import asyncpg
from dotenv import load_dotenv
from fastmcp import FastMCP

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(BASE_DIR, ".env"))

mcp = FastMCP(
    name="Expense Tracker Server",
    instructions="""
    This MCP server manages personal expense records.

    Use this server to:
    - Add a new expense with date, amount, category, subcategory, and note.
    - View all saved expenses from newest to oldest.

    Dates should be provided in YYYY-MM-DD format.
    Amount should be a positive number.
    """
)

CATEGORIES_PATH = os.path.join(BASE_DIR, "categories.json")
DATABASE_URL = os.getenv("DATABASE_URL")


async def get_connection() -> asyncpg.Connection:
    """Create a PostgreSQL connection for one database operation."""
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL must be set in .env locally or in FastMCP Cloud "
            "environment variables."
        )

    return await asyncpg.connect(DATABASE_URL)


async def init_db():
    """Create the expenses table if it does not already exist."""
    conn = await get_connection()

    try:
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS expenses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                date DATE NOT NULL,
                amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
                category VARCHAR(100) NOT NULL,
                subcategory VARCHAR(100) DEFAULT '',
                note TEXT DEFAULT '',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)
    finally:
        await conn.close()


@mcp.tool()
async def add_expense(
    date: str,
    amount: float,
    category: str,
    subcategory: str = "",
    note: str = ""
) -> dict:
    """
    Add a new expense record to the expense tracker.

    Args:
        date: Expense date in YYYY-MM-DD format. Example: 2026-07-02.
        amount: Expense amount as a positive number. Example: 250.50.
        category: Main expense category. Example: Food, Travel, Shopping, Bills.
        subcategory: Optional detailed category. Example: Lunch, Taxi, Electricity.
        note: Optional description of the expense.

    Returns:
        A success response with the generated expense ID, or an error response.
    """
    if amount <= 0:
        return {
            "status": "error",
            "message": "Amount must be greater than zero."
        }

    try:
        expense_date = date_type.fromisoformat(date)

        conn = await get_connection()
        try:
            expense_id = await conn.fetchval(
                """
                INSERT INTO expenses (date, amount, category, subcategory, note)
                VALUES ($1, $2, $3, $4, $5)
                RETURNING id
                """,
                expense_date,
                amount,
                category,
                subcategory,
                note,
            )
        finally:
            await conn.close()

        return {
            "status": "success",
            "message": "Expense added successfully.",
            "expense_id": expense_id
        }

    except ValueError:
        return {
            "status": "error",
            "message": "Date must be in YYYY-MM-DD format."
        }
    except Exception as error:
        return {
            "status": "error",
            "message": f"Could not add expense: {error}"
        }


@mcp.tool()
async def list_expenses() -> list[dict]:
    """Retrieve all saved expenses from newest to oldest."""
    conn = await get_connection()

    try:
        rows = await conn.fetch("""
            SELECT id, date, amount, category, subcategory, note, created_at
            FROM expenses
            ORDER BY created_at DESC
        """)

        return [
            {
                "id": row["id"],
                "date": row["date"].isoformat(),
                "amount": float(row["amount"]),
                "category": row["category"],
                "subcategory": row["subcategory"],
                "note": row["note"],
                "created_at": row["created_at"].isoformat(),
            }
            for row in rows
        ]
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(init_db())
    mcp.run(transport="http", host="0.0.0.0", port=8000)